spring:
  application:
    name: user-command-service
server:
  port: 0

eureka:
  instance:
    instance-id: user-command-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka