spring:
  application:
    name: user-command-service
server:
  port: 64412

eureka:
  instance:
    instance-id: user-command-service-instance
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka